### ISSUE TITLE
Serialize/Deserialize 64bit numbers

### ISSUE THREAD

**Issue by tbsuht** [CESNET/libyang-python#106]
Hi,

when converting a Node to a dict via `print_dict`, 64bit values are not converted to a String.
The documentation states: 
```
The format is inspired by the YANG JSON format described in :rfc:`7951` but has
some differences:

* int64 and uint64 values are represented by python int values
  instead of string values.
```

Now the problem for me is, if I take the output from `print_dict` and use it again in `parse_data_mem` this will result in an error like e.g. for 64bit values:
`libyang.util.LibyangError: failed to parse data tree: Invalid non-num64-encoded uint64 value "0".`

If I manually change the values to strings it is working. How to deal with this? Why are strings not used in this case as the RFC suggests?

**Comment by tbsuht** [comment]
To give a reproducer, you can use this diff:

```
diff --git a/tests/test_data.py b/tests/test_data.py
index 10d9045..1113e7c 100644
--- a/tests/test_data.py
+++ b/tests/test_data.py
@@ -426,10 +426,11 @@ def test_data_to_dict_config(self):
         dnode = self.ctx.parse_data_mem(self.JSON_CONFIG, "json", validate_present=True)
         self.assertIsInstance(dnode, DContainer)
         try:
-            dic = dnode.print_dict()
+            dic = dnode.print_dict(strip_prefixes=False)
         finally:
             dnode.free()
-        self.assertEqual(dic, self.DICT_CONFIG)
+        # self.assertEqual(dic, self.DICT_CONFIG)
+        self.ctx.parse_data_mem(json.dumps(dic), "json")
 
     def test_data_to_dict_rpc_input(self):
         in_data = '{"yolo-system:format-disk": {"disk": "/dev/sda"}}'
diff --git a/tests/yang/yolo/yolo-system.yang b/tests/yang/yolo/yolo-system.yang
index ef61254..4891e98 100644
--- a/tests/yang/yolo/yolo-system.yang
+++ b/tests/yang/yolo/yolo-system.yang
@@ -127,7 +127,7 @@ module yolo-system {
       description
         "The speed.";
       if-feature turbo-boost;
-      type uint32;
+      type uint64;
       default 4321;
     }
 

```

Execution:
```
$ python -m unittest tests.test_data.DataTest.test_data_to_dict_config
E
======================================================================
ERROR: test_data_to_dict_config (tests.test_data.DataTest.test_data_to_dict_config)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/nd-dev/libyang-python/tests/test_data.py", line 426, in test_data_to_dict_config
    dnode = self.ctx.parse_data_mem(self.JSON_CONFIG, "json", validate_present=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nd-dev/libyang-python/libyang/context.py", line 411, in parse_data_mem
    return self.parse_data(
           ^^^^^^^^^^^^^^^^
  File "/workspaces/nd-dev/libyang-python/libyang/context.py", line 390, in parse_data
    raise self.error("failed to parse data tree")
libyang.util.LibyangError: failed to parse data tree: Invalid non-num64-encoded uint64 value "1234".

----------------------------------------------------------------------
Ran 1 test in 0.006s

FAILED (errors=1)
```

**Comment by tbsuht** [comment]
Ok, this question was kind of already asked here: https://github.com/CESNET/libyang-python/issues/60

What would be the recommendation, if the data should be mapped to json?
Would it be enough to adjust the data type handling in this [block](https://github.com/CESNET/libyang-python/blob/master/libyang/data.py#L1070)?

**Comment by tbsuht** [comment]
I guess `print()` (instead of `print_dict`) is what I need ...
