### ISSUE TITLE
can i use libyang-python in python3.11.7

### ISSUE THREAD

**Issue by excitedstate** [CESNET/libyang-python#109]
When i import libyang in python3.11.7 interpreter, it shows the following message:
```
Python 3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libyang as ly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/venv/lib/python3.11/site-packages/libyang/__init__.py", line 7, in <module>
    from .context import Context
  File "/path/to/venv/lib/python3.11/site-packages/libyang/context.py", line 9, in <module>
    from _libyang import ffi, lib
ImportError: /path/to/venv/lib/python3.11/site-packages/_libyang.cpython-311-x86_64-linux-gnu.so: undefined symbol: lyd_get_value
```
And my libyang project version is 2.1.148, library version is 2.46.3. I installed the library in `/usr/local/include`, so the installation succeeded (command: pip install libyang) as following:
```
Collecting libyang
  Downloading libyang-2.8.4.tar.gz (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 kB 393.8 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi in /path/to/venv/lib/python3.11/site-packages (from libyang) (1.16.0)
Requirement already satisfied: pycparser in /path/to/venv/lib/python3.11/site-packages (from cffi->libyang) (2.21)
Building wheels for collected packages: libyang
  Building wheel for libyang (pyproject.toml) ... done
  Created wheel for libyang: filename=libyang-2.8.4-cp311-cp311-linux_x86_64.whl size=217465 sha256=12fc54b8b08cd67602a1c575cba0ab90eb1bebdab0437509bf0f0003db10ec70
  Stored in directory: /home/bing/.cache/pip/wheels/e3/e9/a4/532230096c57b3bcf60d4370b36d02c8a545ba8eb4e2717ba5
Successfully built libyang
Installing collected packages: libyang
Successfully installed libyang-2.8.4
```
`python==3.11.7`
`cffi==1.16.0`
`libyang==2.8.4` (libyang-python)
should i downgrade the python version or libyang version?

**Comment by excitedstate** [comment]
I tried to reinstall lastest libyang and removed the old one, the problem changed: `ImportError: libyang.so.2: cannot open shared object file: No such file or directory `
I set `LD_LIBARAY_PATH`, the problem was solved.
