### ISSUE TITLE
Build for aarch64

### ISSUE THREAD

**Issue by tbsuht** [CESNET/libyang-python#70]
Hi,

I want to use those bindings on an ARM64 system but have problems to figure out how to do it.
I got as far as this, providing the arm binaries which are available locally:
```
LIBYANG_HEADERS=/home/user/.conan2/p/libyaeb22fb6807152/p/include \
LIBYANG_LIBRARIES=/home/user/.conan2/p/libyaeb22fb6807152/p/lib \
LIBYANG_EXTRA_CFLAGS="-I /home/user/.conan2/p/pcre215428838101c9/p/include" \
LIBYANG_EXTRA_LDFLAGS="-L /home/user/.conan2/p/libyaeb22fb6807152/p/lib" \
pip install libyang
```

but the build will use the wrong compiler
```
x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC [...]
/usr/bin/ld: skipping incompatible /home/user/.conan2/p/libyaeb22fb6807152/p/lib/libyang.so when searching for -lyang
/usr/bin/ld: skipping incompatible /home/user/.conan2/p/libyaeb22fb6807152/p/lib/libyang.so when searching for -lyang
```

is it possible to define a toolchain somewhere? I couldn't find something in the docs of cffi.

**Comment by tbsuht** [comment]
Got it working using `CC` env variable.

But now its failing to import the module:
```
>>> import libyang
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/venv/lib/python3.11/site-packages/libyang/__init__.py", line 7, in <module>
    from .context import Context
  File "/opt/venv/lib/python3.11/site-packages/libyang/context.py", line 9, in <module>
    from _libyang import ffi, lib
ModuleNotFoundError: No module named '_libyang'
```

**Comment by tbsuht** [comment]
Found the root cause:
`/opt/venv/lib/python3.11/site-packages/_libyang.cpython-311-x86_64-linux-gnu.so` is part of the wheel. But this should be `/opt/venv/lib/python3.11/site-packages/_cffi_backend.cpython-311-aarch64-linux-gnu.so`. I've copied the so file to this filepath, and then the import is working.

Where is this platform name coming from?
I created the wheel via:
```
CC=/usr/bin/aarch64-linux-gnu-gcc \
LIBYANG_HEADERS=/home/user/.conan2/p/libyaeb22fb6807152/p/include \
LIBYANG_LIBRARIES=/home/user/.conan2/p/libyaeb22fb6807152/p/lib \
LIBYANG_EXTRA_CFLAGS="-I /home/user/.conan2/p/pcre215428838101c9/p/include" \
LIBYANG_EXTRA_LDFLAGS="-L /home/user/.conan2/p/libyaeb22fb6807152/p/lib" \
python3 setup.py bdist_wheel --plat-name=linux-aarch64
```

**Comment by tbsuht** [comment]
Ok I have to run it using QEMU inside a aarch64 rootfs. Now its working :)
